# Generated by Django 3.2.5 on 2021-07-30 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('user', '0003_alter_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='group.groups'),
        ),
    ]
